version: '3'

#NETWORK
networks:
  inception:
    driver: bridge
    name: inception

#VOLUME
volumes:
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/wordpress
  mdb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/mariadb
  wp_log:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/wordpress_log
  ng_cert:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/nginx_cert
  cert_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/certbot_data

services:
#MARIADB
  mariadb:
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    image: mariadb
    container_name: mariadb
    volumes:
      - mdb:/var/lib/mysql
    env_file : .env
    networks: 
      - inception
    restart: always

#WORDPRESS
  wordpress:
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile 
    image: wordpress
    hostname: wordpress
    container_name: wordpress
    volumes:
      - wp:/var/www/wordpress
      - wp_log:/var/log/
    depends_on:
       mariadb:
         condition: service_healthy
    env_file : .env
    networks:
      - inception
    restart: always

#NGINX
  nginx:
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    volumes:
      - wp:/var/www/wordpress
      - ng_cert:/etc/letsencrypt
      - cert_data:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - certbot
    env_file : .env
    networks:
      - inception
    restart: unless-stopped

#PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    links:
      - mariadb
    depends_on:
      - mariadb
      - nginx
    env_file : .env
    networks:
      - inception
    restart: always

#CertBot
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    volumes:
      - ng_cert:/etc/letsencrypt/:rw
      - cert_data:/var/www/certbot/:rw