- name: Deploiement CLOUD-1
  hosts: myhosts
  tasks:
    - name: Copy remote file
      copy:
        src: ~/Documents/42/cloud-1/srcs
        dest: ~/cloud-1/
        owner: jguigli
        group: jguigli
        mode: 0644

    - name: Install Docker and Docker Compose
      become: yes
      script: install_docker.sh

    - name: Launch docker-compose
      shell: make > /tmp/docker-compose.log 2>&1
      args:
        chdir: ~/cloud-1/srcs