- name: Deploiement CLOUD-1
  hosts: myhosts
  tasks:
    - ansible.builtin.debug:
        msg: "DOMAIN_NAME: {{ env }}"

- name: Check system requirements
  ansible.builtin.import_playbook: playbook/system_requirements.yaml

- name: Copy file to remote
  ansible.builtin.import_playbook: playbook/copy_remote_file.yaml

- name: Launch application
  ansible.builtin.import_playbook: playbook/launch_app.yaml

- name: Launch Certbot
  ansible.builtin.import_playbook: playbook/certbot.yaml
