- name: System requirements
  hosts: myhosts
  tasks:
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Check if "make" is already installed
      ansible.builtin.debug:
        msg: "'make' is already installed, skipping..."
      when: "'make' in ansible_facts.packages"

    - name: Install the package "make"
      become: yes
      ansible.builtin.apt:
        name: make
      when: "'make' not in ansible_facts.packages"

    - name: Check if "docker" is already installed
      ansible.builtin.debug:
        msg: "'docker' is already installed, skipping..."
      when: "'docker.io' in ansible_facts.packages"

    - name: Install Docker and Docker Compose
      script: ../install_docker.sh
      when: "'docker.io' not in ansible_facts.packages"

    - name: Reboot machine
      become: yes
      ansible.builtin.reboot:
